version = 0.1

[default.deploy.parameters]
stack_name = "fbp-lambda-v2"
resolve_s3 = true
s3_prefix = "fbp-lambda-v2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"my-fbp.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
