version = 0.1

[default.build.parameters]
template_file = "min.yaml"

[default.deploy.parameters]
stack_name = "fbp-lambda"
resolve_s3 = true
s3_prefix = "fbp-lambda"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "FBPUsersTableName=\"FBP-Users\" FBPConfigTableName=\"FBP-Config\" FBPScheduleTableName=\"2025-Schedule\" FBPPicksTableName=\"FBP-Picks\" FBPLogsTableName=\"2025-Log\" FBPWeeklyResultsTableName=\"FBP-Weekly-Results\" FBPWeeklyResultsWeekIndexName=\"WeekIndex\" S3BucketName=\"my-fbp.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
