AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scratch

  Sample SAM Template for scratch

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  CreateOrder:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CreateOrder
      Handler: com.fbp.CreateOrderLambda::createOrder
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      # Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      #   Variables:
      #     PARAM1: VALUE
      Events:
        CreateOrder:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /createOrder
            Method: POST
#  Replace CreateOrder with something like AddFBPUser
#  Remember to add the appropriate IAM permissions
#  
#  Define your dynamo DB access here as another lambda function