AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fbp-lambda
  Sample SAM Template for fbp-lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    # Environment:
    #   Variables:
    #     FBP_USERS_TABLE_NAME: !Ref FBPUsersTableName  # Fixed: Added ! and corrected parameter name
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'https://my-fbp.com'"

Parameters:
  FBPUsersTableName:  # Fixed: Corrected spelling (was FBPusersTableName)
    Type: String
    Default: FBPUsers

Resources:
  FBPUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FBPUsersTableName
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AddFBPUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./AddFBPUser
      Handler: com.fbp.AddFBPUser::createFBPUser
      Runtime: java17
      Architectures:
        - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FBPUsersTableName
      Environment:
        Variables:
          FBPUsers: !Ref FBPUsersTableName
      Events:
        AddFBPUser:
          Type: Api
          Properties:
            Path: /addFBPUser
            Method: POST