AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fbp-lambda
  Sample SAM Template for fbp-lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      # AllowOrigin: "'https://my-fbp.com'"
      AllowOrigin: "'*'"

Parameters:
  FBPUsersTableName:  # Fixed: Corrected spelling (was FBPusersTableName)
    Type: String
    Default: FBP-Users
  FBPScheduleTableName:  # Added parameter for schedule table
    Type: String
    Default: 2025-Schedule
  FBPSpreadTableName:  # Added parameter for spread table
    Type: String
    Default: 2025-Spread
  FBPConfigTableName:  # Added parameter for config table
    Type: String
    Default: FBP-Config
  FBPPicksTableName:  # Added parameter for picks table
    Type: String
    Default: FBP-Picks

Resources:
  AddFBPUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./AddFBPUser
      Handler: com.fbp.AddFBPUser::addFBPUser
      Runtime: java11
      Architectures:
        - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FBPUsersTableName
      Environment:
        Variables:
          FBPUsers: !Ref FBPUsersTableName
      Events:
        AddFBPUser:
          Type: Api
          Properties:
            Path: /addFBPUser
            Method: POST
  SaveFBPPicks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./SaveFBPPicks
      Handler: com.fbp.SaveFBPPicks::saveFBPPicks
      Runtime: java11
      Architectures:
        - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FBPPicksTableName
      Environment:
        Variables:
          FBPPicksTableName: !Ref FBPPicksTableName
      Events:
        SaveFBPPicks:
          Type: Api
          Properties:
            Path: /saveFBPPicks
            Method: POST

  GetFBPUser:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./GetFBPUsers
        Handler: com.fbp.GetFBPUsers::getFBPUser
        Runtime: java11
        Architectures:
          - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
        Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FBPUsersTableName
        Environment:
          Variables:
            FBPUsers: !Ref FBPUsersTableName
        Events:
          GetFBPUser:
            Type: Api
            Properties:
              Path: /getFBPUser
              Method: GET

  GetPickSheet:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./GetPickSheet
        Handler: com.fbp.GetPickSheet::getPickSheet
        Runtime: java11
        Architectures:
          - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
        Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FBPScheduleTableName
        - DynamoDBReadPolicy:
            TableName: !Ref FBPConfigTableName
        Environment:
          Variables:
            FBPScheduleTableName: !Ref FBPScheduleTableName
            FBPConfigTableName: !Ref FBPConfigTableName
        Events:
          GetPickSheet:
            Type: Api
            Properties:
              Path: /getPickSheet
              Method: GET
  GetScheduleSheet: 
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./GetScheduleSheet
        Handler: com.fbp.GetScheduleSheet::getScheduleSheet
        Runtime: java11
        Architectures:
          - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
        Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FBPScheduleTableName
        - DynamoDBReadPolicy:
            TableName: !Ref FBPConfigTableName
        Environment:
          Variables:
            FBPScheduleTableName: !Ref FBPScheduleTableName
            FBPConfigTableName: !Ref FBPConfigTableName
        Events:
          GetScheduleSheet:
            Type: Api
            Properties:
              Path: /getScheduleSheet
              Method: GET  

Outputs:
  addfbpuserfunction:
    Description: "add fbp user lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addfbpuser"
  addfpbuserfunctionarn:
    Description: "add fbp user lambda function arn"
    Value: !GetAtt AddFBPUser.Arn
  addfpbuserfunctionrole:
    Description: "add fbp user lambda function role"
    Value: !GetAtt AddFBPUserRole.Arn
  getfbpuserfunction:
    Description: "get fbp user lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getfbpuser"
  getfpbuserfunctionarn:
    Description: "get fbp user lambda function arn"
    Value: !GetAtt GetFBPUser.Arn
  getfpbuserfunctionrole:
    Description: "get fbp user lambda function role"
    Value: !GetAtt GetFBPUserRole.Arn
  getschedulesheetfunction:
    Description: "get schedule sheet lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getScheduleSheet"
  getschedulesheetfunctionarn:
    Description: "get schedule sheet lambda function arn"
    Value: !GetAtt GetScheduleSheet.Arn
  getschedulesheetfunctionrole:
    Description: "get schedule sheet lambda function role"
    Value: !GetAtt GetScheduleSheetRole.Arn
  getpicksheetfunction:
    Description: "get pick sheet lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getPickSheet"
  getpicksheetfunctionarn:
    Description: "get pick sheet lambda function arn"
    Value: !GetAtt GetPickSheet.Arn
  getpicksheetfunctionrole:
    Description: "get pick sheet lambda function role"
    Value: !GetAtt GetPickSheetRole.Arn
  savefbppicksfunction:
    Description: "save fbp picks lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/saveFBPPicks"
  savefbppicksfunctionarn:
    Description: "save fbp picks lambda function arn"
    Value: !GetAtt SaveFBPPicks.Arn
  savefbppicksfunctionrole:
    Description: "save fbp picks lambda function role"
    Value: !GetAtt SaveFBPPicksRole.Arn

