AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fbp-lambda
  Sample SAM Template for fbp-lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
  Api:
    Name: fbpLambda
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'https://my-fbp.com'"

Parameters:
  FBPUsersTableName:  # Fixed: Corrected spelling (was FBPusersTableName)
    Type: String
    Default: FBPUsers

Resources:
  FBPUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FBPUsersTableName
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AddFBPUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./AddFBPUser
      Handler: com.fbp.AddFBPUser::createFBPUser
      Runtime: java11
      Architectures:
        - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FBPUsersTableName
      Environment:
        Variables:
          FBPUsers: !Ref FBPUsersTableName
      Events:
        AddFBPUser:
          Type: Api
          Properties:
            Path: /addFBPUser
            Method: POST

  GetFBPUser:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./GetFBPUsers
        Handler: com.fbp.GetFBPUsers::getFBPUser
        Runtime: java11
        Architectures:
          - x86_64
      # Remove MemorySize here since it's in Globals
      # Remove Environment here since it's in Globals
        Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FBPUsersTableName
        Environment:
          Variables:
            FBPUsers: !Ref FBPUsersTableName
        Events:
          GetFBPUser:
            Type: Api
            Properties:
              Path: /getFBPUser
              Method: GET
Outputs:
  FBPUsersTable:
    Description: "FBP Users Table"
    Value: !Ref FBPUsersTable

  AddFBPUserFunction:
    Description: "Add FBP User Lambda Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addFBPUser"
  AddFPBUserFunctionARN:
    Description: "Add FBP User Lambda Function ARN"
    Value: !GetAtt AddFBPUser.Arn
  AddFPBUserFunctionRole:
    Description: "Add FBP User Lambda Function Role"
    Value: !GetAtt AddFBPUserRole.Arn
  GetFBPUserFunction:
    Description: "Get FBP User Lambda Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getFBPUser"
  GetFPBUserFunctionARN:
    Description: "Get FBP User Lambda Function ARN"
    Value: !GetAtt GetFBPUser.Arn
  GetFPBUserFunctionRole:
    Description: "Get FBP User Lambda Function Role"
    Value: !GetAtt GetFBPUserRole.Arn

